sudo: required
services:
- docker
env:
  global:
  - DOCKER_REPO=mohamedmeskine/timemanagerapi
  - secure: Au9u6pOYc1TsnDk2z2amTylk5FKdvL7aN/qSr7DFK/6N8SabF0mbILYPoOmcDJdzywQSi+TTmm+/nI65TxWmOOGgusZws6iFcaQhI/N/lKy6aIq3oNkkRqHfSJf5Q3Gn3BvDuxeCsmezodoja4lSHKHpOwVzVizaismF48b3AnjtpO/sy4KmPJAi1T+g7crLUwOqWUovx0acaYrD8NotRH9tJCltUZ3ZFLi8vzKhCn+7sS3vaWXXzrkvN70hbhqbjBNXA7YuWuE301tf/xD3uZH/g3Aid33q2/XhrbTi6lUqMV2sPuUPLX+xcUVa7lDiO/coKpP+olv4Gre5wC7DaGfoqXZKna4Abb0PO7ndvq625errI19zal5r4xx02hS3JoX9Tw7kbyFpyvigvpAzu1WjMRnePeNCdS+PI1A9cnW6g68pGnx/X9DXpdiUuvTuBu+cGH3EAGad2yw5D+r+FJOk2DxOky5dUBAkeJeyqzo3yom8EogPksInJQ6WfkzvxVvGR9BSGae62fwzzFO4BXtQv2PIdRBgocASVmOcHDfXClTBumJMVSX7rtRFIi3DcyQeRcE0n0njCSqgTOGdmU21sWc8Gc1P79T3pBvXAvCPC8K5Ogs5U8NPU2ByyxGpq/AK2+kcNrrMD65MT29lroqXCkETPZE9wWS4OhaJROk=
  - secure: kuVHEvQ3zZL676d0AugKtR6NOEROCPBxRH1qa2jI+MSe2tAW7Y0YSErALlzF5tsjug29u6UH9g3iF+QWRP+dHuHJ+iJViEiic1DkT4i8rcyBrnnhLOXsQbRGkDtRjmie5Vm7no5eOc2SCmkGwxt2lG3Oi6Sarg2yMcO2Yy7F0L0Z6B+DEaCQaSSTSGYNswcrzh/qQNrB/ukstbAlak8OiM1Wf2oIrpJ99T53eqyCU1hTKs4bg3wXUwQrqyPtPzy0jlY/ezKKNIls53LlftryoKxlPvDwHdEmc+4KoyAdljfqJ7jIqkQxX51hon2AZSo4CXDrC9YFyGmSNRZj6g96MB7pjzlQVCHKD12nxs92ElPvp0QSg8aAYpIvVabL9LiK1KewNip/As8vwiEoHs3qgJXSsLHTeigyCOori5fz86cY5L/OZk6W/prgGgeESOla5vXO4C8GrJ/8ZY/XMErMFBQwUIQpjSbhFHd6kuL0UmbpTTS8QfsP5cc2/dVSCAdShwnr2/QXQwFy2pLYoIJSL+kcz6iCkKaKaufCazE2fCc4exvYwAEsA90vRJ4Xhw8f4eLg65NvJP5x5pnaYWEh4xsB3GEvXdfWePM1Z2aC6LGqNyU7PprxB0iHZ73bYeh+hbo0O41iCOATkMWXZvhhd48bsV5n4icfYDO8vBE/z24=
before_install:
- export PATH=$PATH:$HOME/.local/bin
script:
- docker build -t $DOCKER_REPO .
deploy:
  provider: script
  script: bash docker_push.sh
  on:
    branch: master
