name: CI to Docker Hub
on:
  push:
    branches: [ main ]
    
jobs:
 build__push_API:
    runs-on: ubuntu-latest
    steps:
    
      - name: Check Out Repo API
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
        with:
          driver: docker 

      - name: Build and push timemanagerapi
        id: docker_build_timemanagerapi
        uses: docker/build-push-action@v2
        with:
          context: ./timeManagerAPI
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/timemanagerapi:latest

      - name: Image digest timemanagerapi
        run: echo ${{ steps.docker_build.outputs.digest }}

 build_push_Front:
    runs-on: ubuntu-latest
    steps:

      - name: Check Out Repo API
        uses: actions/checkout@v2
        
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
          
      - name: Build and push front
        id: docker_build_front
        uses: docker/build-push-action@v2
        with:
          context: ./front
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/timemanagerfront:latest

      - name: Image digest timemanagerfront
        run: echo ${{ steps.docker_build.outputs.digest }}
